package com.sentragizi.modules.inspector.ui.wizard;

import com.sentragizi.modules.inspector.repositories.InspectionRepository;
import com.sentragizi.modules.inspector.ui.InspectorMainFrame;
import com.sentragizi.modules.inspector.ui.wizard.PanelStage2;
import javax.swing.JOptionPane;

public class PanelQueue extends javax.swing.JPanel {

    InspectorMainFrame frame;
    InspectionRepository repo = new InspectionRepository();
    
    public PanelQueue(InspectorMainFrame f) {
        this.frame = f;
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();

        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblQueue);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnNew.setText("Mulai Inspeksi");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnResume.setText("Lanjut");
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(36, 36, 36)
                        .addComponent(btnResume))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnRefresh)
                    .addComponent(btnResume))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void refresh() {
        tblQueue.setModel(repo.getQueueTable());
    }
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        frame.showPage("STAGE1");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        // Cek baris mana yang dipilih user
        int row = tblQueue.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih antrean masak dulu!");
            return;
        }
        
        // Ambil data dari tabel (Kolom 0 = UUID, Kolom 3 = Status)
        String uuid = tblQueue.getValueAt(row, 0).toString();
        String status = tblQueue.getValueAt(row, 3).toString();
        
        // Pastikan statusnya benar (COOKING artinya sudah lolos tahap 1)
        if (status.equals("COOKING") || status.equals("DRAFT")) {
             
             // Ambil akses ke Panel Stage 2
             PanelStage2 p2 = frame.getPanelStage2();
             
             if (p2 != null) {
                 // Set UUID ke Panel 2 agar dia tahu batch mana yang sedang dikerjakan
                 p2.setUUID(uuid);
                 
                 // Pindah halaman
                 frame.showPage("STAGE2");
             } else {
                 JOptionPane.showMessageDialog(this, "Error: Panel Stage 2 belum dimuat!");
             }
             
        } else {
             JOptionPane.showMessageDialog(this, "Batch ini tidak bisa dilanjutkan (Status: " + status + ")");
        }

    }//GEN-LAST:event_btnResumeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnResume;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQueue;
    // End of variables declaration//GEN-END:variables
}
